export type Technologies = 'typescript'
    | 'javascript'
    | 'docker'
    | 'nest'
    | 'node'
    | 'postgres'
    | 'redis'
    | 'mongo'
    | 'git'
    | 'nginx'
    | 'react'
    | 'graphql'
    | 'preact';
